### ISSUE TITLE
Jump from part to MF sometimes doesn't work

### ISSUE THREAD

**Issue by xaraxarax** [rgriebl/brickstore#629] opened 2022-11-22 15:16 UTC
https://user-images.githubusercontent.com/79638214/203350956-8fcc3ff7-a2aa-495e-bbec-8b342be91e4e.mp4

**Comment by rgriebl** [comment] 2022-11-22 15:44
I think this is a duplicate of #627. Could you please try the latest dev build to see if it fixes the problem?
https://github.com/rgriebl/brickstore/actions/runs/3493282271

**Comment by xaraxarax** [comment] 2022-11-22 15:52
same behavior in #882, seems to affect all heads without having tried all

**Comment by xaraxarax** [comment] 2022-11-22 16:30
works like charm ;) without filtering, just select the part from the list and jump works like charm

**Closed** 2022-11-22 21:42 UTC

**Comment by xaraxarax** [comment] 2022-11-22 22:09
👍
