### ISSUE TITLE
Print/PDFPrint with Standard Print Template gives TypeError

### ISSUE THREAD

**Issue by xaraxarax** [rgriebl/brickstore#273] opened 2021-03-03 10:07 UTC
![grafik](https://user-images.githubusercontent.com/79638214/109789172-5908c500-7c10-11eb-8ff4-f2d2006af0ba.png)

**Comment by paramecie** [comment] 2021-03-03 11:00
No problem here.
More details? A new file made in the new BrickStore? A BrickStock file? An imported file? A downloaded inventory? System? Does it work sometimes or never? (etc) would help I guess...

**Comment by rgriebl** [comment] 2021-03-03 11:00
Duplicate of #215 ... fixed in dev builds already

**Closed by rgriebl** 2021-03-03 11:00 UTC

**Comment by paramecie** [comment] 2021-03-03 11:05
@xaraxarax please check this page and download the latest build:
https://github.com/rgriebl/brickstore/actions

Example:
https://github.com/rgriebl/brickstore/actions/runs/615983206

**Comment by xaraxarax** [comment] 2021-03-03 11:41
thank you, but unfortunately no remarks ... it's another thing

@paramecie I'm authenticated, but i never find this build in an easy way, maybe i overlook an icon, link, indicator, whatever, that an build is behind the action?

**Comment by paramecie** [comment] 2021-03-03 12:39
@xaraxarax 

Ah no remarks, that's the template problem.

I'm not sure if creating templates is available right now (and documented), as it's a relatively new printing system...

About the actions page, you just have to open this page from time to time.
https://github.com/rgriebl/brickstore/actions
There are builds (corrections, improvements) almost every day, but "official" releases are rare...
