### ISSUE TITLE
Program crashes when parting out into same window

### ISSUE THREAD

**Issue by AllesMeins** [rgriebl/brickstore#102] opened 2021-01-18 21:27 UTC
The current release (2021.1.4) crashes with a SegFault on Linux when parting out into the same window.

Steps to reproduce:
1. Open a new document
2. Add any set
3. Select Part Out
4. Confirm with "Yes" to part out the item into the current document
5. The program crashes with a Segmentation Fault
The problem does not occur when choosing to part out into a new document.

$ brickstore 
Loading database from "/home/gedinixan/.cache/BrickStore/"
Colors    :      182  (      13832 bytes)
Types     :        8  (        352 bytes)
Categories:      939  (      33804 bytes)
Items     :   144087  (   14408700 bytes)
Loading scripts from directory: "/home/gedinixan/.local/share/BrickStore/extensions"
Loading scripts from directory: ":/extensions"
  [ ok ] ":/extensions/standard-print-template.bs.qml"
Loading scripts from directory: "/usr/share/brickstore/extensions"
Segmentation fault (core dumped)

$ dmesg
[ 6499.464580] traps: brickstore[48549] general protection fault ip:55e9c383e514 sp:7fff308b3dd8 error:0 in brickstore[55e9c3806000+151000]
[ 6539.590689] traps: brickstore[49479] general protection fault ip:55f114ade514 sp:7ffff9da1d68 error:0 in brickstore[55f114aa6000+151000]
[ 6580.041329] brickstore[51310]: segfault at 18 ip 000055e766d77047 sp 00007ffd0abd1120 error 4 in brickstore[55e766c5a000+151000]
[ 6580.041336] Code: 00 ff ff ff ff 4d 85 ed 74 0b 41 8b 45 08 48 c1 e0 20 48 89 c2 48 8b 43 10 8b 4b 34 4c 8d 75 28 4c 8d a5 c8 00 00 00 4c 89 f7 <48> 0f be 00 81 e1 ff ff ff 00 48 83 c1 01 48 c1 e0 18 48 09 c8 48

I've tried this on two different Systems. One Ubuntu 64bit with the provided package, the other one was compiled from source on Debian Bullseye. Both showed the same problem.

Is there anything else I can do to help track down the problem? Are there any logs I could provide?

**Comment by rgriebl** [comment] 2021-01-18 22:24
Already fixed, but not released yet. Duplicate of #95

**Closed by rgriebl** 2021-01-18 22:24 UTC

**Comment by paramecie** [comment] 2021-01-18 23:46
@AllesMeins please download the latest build here:
https://github.com/rgriebl/brickstore/actions/runs/494665586

It's a .mid file, a zip one - simply unzip and install it (Windows anyway...) - that should be fixed.
