### ISSUE TITLE
Sort order not right

### ISSUE THREAD

**Issue by Brickadoon** [rgriebl/brickstore#862] opened 2024-04-06 18:33 UTC
Sort order in Description field is misbehaving

Open a new file, go to 'Add items/Part/Slope' (also happens with Slope, Inverted)
Sort by 'Description' column
Slopes of same size are mixed with other sizes (see pic)

**System information**
### BrickStore 2024.4.1 (build: 1211)

* **brickstore.ldraw**: 05 Apr 2024 19:37:39 +0100
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930154)
* **build.date**: 2024-04-05T12:55:13.000
* **build.host**: fv-az981-840
* **build.number**: 1211
* **build.qt.version**: 6.6.2
* **hw.cpu**: AMD FX(tm)-4100 Quad-Core Processor
* **hw.cpu.arch**: x86_64
* **hw.gpu**: AMD Radeon HD 6450
* **hw.gpu.arch**: amd
* **hw.memory.gb**: 24.0
* **os.arch**: x86_64
* **os.productname**: Windows 10 Version 22H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.6.2
* **windows.tabletmode**: false

![image](https://github.com/rgriebl/brickstore/assets/126781061/c3d45aac-5fd6-4a9a-86cd-7d0fd582136b)

**Comment by rgriebl** [comment] 2024-04-06 18:56
Duplicate of #860

**Closed** 2024-04-06 18:56 UTC
