### ISSUE TITLE
Complete loss of an edited file after Remove Split

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#598] opened 2022-09-19 18:36 UTC
Legacy

**This one is serious, data loss!**
It already happened to me.
I was searching how to reproduce it, which is why I opened #597 

100% reproductible
* Open any file
* Copy a few Lots
* Click Split Horizontally
* You must have 2 identical windows and the right one is highlighted
* Click New file: it shows a blank file on the right
* Paste the above lots, it shows an edited file : **Untitled***
* Click Remove Split

The new file is closed and all data is lost.

Update: same if you simply open a second file on the right window and edit it.
When clicking Remove Split the edition is lost.

**Comment by rgriebl** [comment] 2022-09-20 10:47
This bug is actually in BrickStore since I added the split feature 9 months ago, but you're the first to report it.
It won't be an easy fix, because I built the whole one-document/multiple-views architecture around a wrong assumption (as I have realized now).
I'll most likely do a 9.3 release soon, fixing some more immediate problems and rather take my time on this one to get it right.

**Comment by rgriebl** [comment] 2022-09-28 22:31
I have a potential fix for this issue: https://github.com/rgriebl/brickstore/actions/runs/3147159624
I tried to backport it to the legacy version for you to test, but BrickStore's internals changed too much.

This fix changes a lot of things around the construction and destruction order of document views, so I would be happy if someone could play around with and see if it works. It does seem to work as intended in my (limited) testing.

**Comment by paramecie** [comment] 2022-09-29 14:24
> I tried to backport it to the legacy version for you to test

Million thanks for the attempt Robert!
No problem, and yes it'd be interesting some people test this run!

**Closed** 2022-10-03 16:48 UTC
