### ISSUE TITLE
Strange "no color"

### ISSUE THREAD

**Issue by paramecie** [rgriebl/brickstore#45] opened 2021-01-06 22:31 UTC
I played with the VERY fine Known colors, tested the Only Modulex also... then, I really don't know why, it happened this "no color":

![image](https://user-images.githubusercontent.com/32078594/103826444-252d7b00-5077-11eb-9f68-9a3f7bbf5d01.png)

See the absence of color name or indication, and the red/white band.

But no idea how I did this, sorry :-(

**Note also the bizarre size of the picture.**

**Comment by rgriebl** [comment] 2021-01-18 21:27
I also have no idea what went wrong there. Closing for now, since I cannot reproduce it.

**Closed by rgriebl** 2021-01-18 21:27 UTC

**Comment by paramecie** [comment] 2021-01-18 23:24
> since I cannot reproduce it.

... me neither!
