### ISSUE TITLE
Unable to Import Orders Placed (App Imports Orders Received)

### ISSUE THREAD

**Issue by polstarbl** [rgriebl/brickstore#769] opened 2023-09-01 01:07 UTC
I have updated the app (BrickStore 2023.8.1 (build: 1059)) but for several weeks it does not import orders placed (as a buyer). Instead, it only imports orders received (as a seller). The app is updated and there is no problem with the login to BrickLink as I can access all orders received. When searching for an order number (order placed as a buyer), it says "Last update failed: Could not parse the received order XML data: XML parse error line 7317, column 29; Expected '#' or '[a-zA-Z]', but got '[0-9]'.  
How can this issue be resolved? Thanks in advance.

**Comment by ZZJHONS** [comment] 2023-09-01 06:37
I did import placed and received orders correctly, maybe this error is because one item in one order has a comment with a strange symbol that Brickstore can't process (for now...?)

Try to download orders manually and import as xml with this link to see which one fails:
https://www.bricklink.com/orderExcel.asp?orderType=placed

Then share here the problem one.

**Comment by rgriebl** [comment] 2023-09-22 17:31
Duplicate of #615
Still a BrickLink bug, but the chances of them fixing all their broken XML escaping after all these years is probably zero.
Nothing I can do about though.

**Closed by rgriebl** 2023-09-22 17:31 UTC
