### ISSUE TITLE
"Show in My Store / CTRL+B+I" shortcut

### ISSUE THREAD

**Issue by legobanker** [rgriebl/brickstore#177] opened 2021-02-11 20:30 UTC
The option to view my store inventory is grayed out.  Is the function: CTRL+B. CTRL+I no longer working?

**Comment by rgriebl** [comment] 2021-02-11 21:58
It should work if you have a lot-id (import your store to verify).
If you want to it work even without a lot-id, then it's a duplicate of #43

**Comment by paramecie** [comment] 2021-02-11 23:10
Oh yes, 100% of all the ones living in me wish #43 :-)

Note that could be another option, like "Search in my Store Inventory" (this one would never have to be disabled, if there's an item of course)

**Comment by rgriebl** [comment] 2021-02-12 00:14
> Oh yes, 100% of all the ones living in me wish #43 :-)

I just had to fix #43 now ... don't need more Sylvains popping out and increasing the issue count exponentially ;)

**Closed by rgriebl** 2021-02-12 00:14 UTC

**Comment by paramecie** [comment] 2021-02-12 00:24
Oh oh - I'm spotted, I'll stay low profile for now on...

**Comment by paramecie** [comment] 2021-02-12 00:44
Build 268, it works well - seems a nice feature.
