### ISSUE TITLE
Brickognize invalid status code 429

### ISSUE THREAD

**Issue by BrickArena** [rgriebl/brickstore#815] opened 2024-01-17 17:56 UTC
**Describe the bug**
When trying to use the integrated BRickognize feature it regularly fails reporting an invalid Status code 429. 

**System information**
Please tell us which system you are running on and which BrickStore version you are using.
In BrickStore, just open `Help` > `System information...`, Click `Copy to clipboard` and then paste  here.

I am using Brickstore 2024.1.2 build 1143

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

**Comment by rgriebl** [comment] 2024-01-17 20:49
429 means "too many requests"

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

Please check with Brickcognize's maintainer, if that means YOU sent to many requests or if it means that the server is overloaded in general. Not a BrickStore problem though.

**Comment by BrickArena** [comment] 2024-01-18 14:44
Hi, Thanks for your response. However, it can't be possible that I sent too many requests as it happens even on my second attempt to scan something.

As a full-time seller I have used this function many many times without any issue and am only experiencing this issue since moving to the the newest version of Brickstore. If I use Brickognize outside of Brickstore it works as expected.

Perhaps I can revert to a previous version and see how I go.


As a separate point I am also noticing that Brickstore is causing a dump overtime I close the application. 

￼

Regards

Keith

Brick Arena

**Comment by BrickArena** [comment] 2024-01-26 11:01
Hi,

Yes, as Keith said I've noticed that after releasing a new version of
Brickstore I started getting a lot of duplicated requests. Currently,
around 50% of requests are duplicated. I've checked a few most active users
and they have either version brickstore/2024.1.2 or brickstore/2024.1.4.

Can I help you with this in any way?

Piotr



czw., 25 sty 2024 o 16:29 Keith Bage ***@***.***> napisał(a):

> Hi Again,
>
> I have been in touch with Piotr from Brickognise and he believes there may
> be an issue with Brickstore sending duplicated requests per image scan.
> Please see his response to me below. He has asked that I copy him on my
> mail thread so that you can discuss further.
>
>
> Regards
>
> Keith
> Brick Arena
>
>
>
>
>
> ------------------------------------------------------
>
> Hi Keith,
>
> Thanks, I'm glad you like Brickognize!
>
> There is a limit of 3 requests per second so it's difficult to exceed it
> during normal usage of Brickstore :) But there is something wrong with the
> new Brickstore update. I noticed that I get many duplicated requests from
> Brickstore (the same photo, from the same user, at the same time). I
> haven't investigated it fully yet and haven't talked to Robert from
> Brickstore yet. But it might be the reason for you getting the 429. You
> make a single request, but for some reason, Brickstore sent multiple of
> them to Briickognize and Brickognize responds with 429 because the rate
> limit was exceeded.
>
> If you have a mail thread with Robert about this issue please add me to
> it. Maybe together we will be able to solve this.
>
> Thanks for telling me about this!
>
> Piotr
>
>

**Comment by BrickArena** [comment] 2024-01-26 12:27
FYI - I first experienced the issue with 2024.1.2 (which is when I reported it. I later updated to 2024.1.4 to see if this solved the problem, but it still remains (though oddly, it doesn’t seem to happen on mornings UK time)).

I suspect the issue was introduced in 2024.1.2.


Regards

Keith

**Comment by rgriebl** [comment] 2024-01-26 14:13
I can't reproduce it. The upload code hasn't changed, the camera access logic hasn't changed, just the way the camera preview is rendered on the screen.

Can you give me a bit more information on what you are doing exactly? (clicking the preview, pressing SPACE, having the dialog pinned, etc.)
What OS are you on?
Can you spot something unusual in the Console? `Extras` -> `Developer Console` (it's in the app menu on macOS)?

**Comment by rgriebl** [comment] 2024-01-26 14:18
Question to Piotr (I've invited him to discuss here directly) ... do you see if this is OS related? the user-agent strings should have the OS name and version appended to them.

**Comment by 360er0** [comment] 2024-01-26 16:53
It doesn't look like it's related to the OS. I can see examples for both Windows and OS X. Right now the only thing I see is related to the number of requests. Users with over 200 **unique** requests have a 70% chance of sending duplicated requests compared to 25% otherwise.

**Comment by BrickArena** [comment] 2024-01-26 17:49
Hi,

The way I typically use Brickstore when adding used inventory (which is often as I’m a full-time seller) is to have the Add Item dialogue open then click the camera icon to open the Brickognise item scanner dialogue. I click the image, which will either… a: Return the identified part or b: give me the 429 error message.


As I’ve mentioned a couple of times what I find odd is that typically when I start my day on a morning I can use the function for an hour or two without issue, I then step away for a while and when I come back I start to scan again and the first one usually works as expected but the second one and subsequent ones will typically fail with the 429 message. Occasionally it will find the searched item again but more often than not it will fail.


I am on MAC OS  Sonoma 14.2


Hope this helps.

**Comment by rgriebl** [comment] 2024-01-26 18:06
This is really strange ... the only thing I found so far is this bug in Qt (https://bugreports.qt.io/browse/QTBUG-114812), where Qt gets confused if the server sends a reply BEFORE the request is fully upload.
I don't think this is happening here, because why would brickognize reply before it has the full image?
@360er0 If you say "duplicate": do you mean exactly 2 times or are there even more? (the bug report in questions says the request is sent 4 times until Qt gives up)

**Comment by 360er0** [comment] 2024-01-26 18:37
Even more, with 10 being the most extreme case.

Here is a distribution for yesterday:

requests | share
-- | --
1 | 66.7%
2 | 17.2%
3 | 14.6%
4-10 | 1.6%

**Comment by 360er0** [comment] 2024-01-26 18:46
Now, that I think about this it is not a surprise that it stops around three because I allow a maximum of three requests per second. So for sure, there are cases with more than three duplicates since I deny them and return 429.

**Comment by tritumBj** [comment] 2024-01-26 19:19
I am experiencing the same issue over and over again. At least since 5 days. Here's the copy of my system information.

### BrickStore 2024.1.4 (build: 1160)

* **brickstore.ldraw**: 18 Oct 2023 07:12:25 +0200
* **brickstore.locale**: de
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930153)
* **build.date**: 2024-01-21T13:15:56.000
* **build.host**: fv-az845-503
* **build.number**: 1160
* **build.qt.version**: 6.6.1
* **hw.cpu**: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: Intel(R) UHD Graphics 620
* **hw.gpu.arch**: intel
* **hw.memory.gb**: 15.8
* **os.arch**: x86_64
* **os.productname**: Windows 11 Version 22H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.6.1
* **windows.tabletmode**: false

**Comment by tritumBj** [comment] 2024-01-26 20:07
Just downgraded to BrickStore 2023.11.2 (build: 1093) and tested it for 1/2 hour. Works like a charm.

**Comment by rgriebl** [comment] 2024-01-26 20:12
@tritumBj @BrickArena Could you please also try this test build: https://github.com/rgriebl/brickstore/actions/runs/7672424571

It's a 2024.1.4 with 3 changes:
1. it prints to the `Developer Console` what it is sending and receiving to/from brickognize
2. it will reset the HTTP request stack on each request
3. @360er0 it has a special User-Agent set: the version is `9999.<request number>`

If the request number on the duplicates stays the same, then something inside Qt is wrong. If the request number increases between the duplicates, then BrickStore's application logic is wrong.

**Comment by tritumBj** [comment] 2024-01-26 20:36
Thank you for your great work. I have installed the new test build and tried to scan a brick. The error message is as follows: "Der Scanvorgang ist fehlgeschlagen". The Developer Console prints the following:

```
CRIT scanner: posted scan 1  ua: "BrickStore/9999.1" at itemscanner.cpp, line 146
CRIT scanner: Called scan while another scan is still is progress at itemscanner.cpp, line 103
CRIT scanner: finished scan 1  status: 200  error: QNetworkReply::NoError at itemscanner.cpp, line 154
```

6 scans later I am reading this:

```
CRIT scanner: posted scan 7  ua: "BrickStore/9999.7" at itemscanner.cpp, line 146
CRIT scanner: Called scan while another scan is still is progress at itemscanner.cpp, line 103
CRIT scanner: finished scan 7  status: 200  error: QNetworkReply::NoError at itemscanner.cpp, line 154
WARN scanner: Brickognize returned an invalid match! type: "part" id: "3731" at itemscanner.cpp, line 207
```

**Comment by rgriebl** [comment] 2024-01-26 20:43
Thanks for testing! In theory the output `Called scan while another scan is still is progress` should never be printed and I cannot for the life of me reproduce this on my machine.
The only way this could happen, if the `imageCaptured` signal is triggered more than once by Qt 6.6.1 (the old 6.5.2 seemed to work ok) with certain camera models.
I'll try to come up with a new test build to for this theory...

**Comment by rgriebl** [comment] 2024-01-27 00:06
@tritumBj @BrickArena 
1. Do you guys have multiple cameras?
2. Do you switch cameras in BrickStore at least once before this problem occurs?

**Comment by BrickArena** [comment] 2024-01-27 00:58
Hi, Sorry I haven’t had a chance to install the test build yet. Will try and do so tomorrow. But I wanted to say that I do have multiple cameras available to me (built in webcam on my Apple Display, iPhone etc.) to use but I only use one ( a Logitech webcam) which I have specially mounted for brickognize purposes and do not switch between this and other cameras.


Regards

Keith

**Comment by rgriebl** [comment] 2024-01-27 01:01
There's now another test build ready to go:
https://github.com/rgriebl/brickstore/actions/runs/7675045401

**Comment by tritumBj** [comment] 2024-01-27 08:08
1. I do have multiple cameras attached to my setup. There is the built-in one, an aux one for my meetings and my Instabrick camera. The aux ones - both of them - are connected via USB.
2. It happens that I am switching cameras. My meeting camera is the default camera. It can happen that I do have to switch.

Thanks for the new built. I have installed it. The error is gone, the scanning works. But I do NOT see a preview video. With neither of the cameras. Can you @BrickArena confirm?

**Comment by BrickArena** [comment] 2024-01-27 10:34
I have tried to test both builds provided but am having lots of issues trying to run them. They typically just shutdown when I try to create a new document. No idea why.


I did manage to test for a short period and got the results below in the developer console.


ARN qml: QML Image: Cannot open: qrc:/Scanner/media-playback-start at CameraPreview.qml, line 20
WARN qml: QML Image: Cannot open: qrc:/Scanner/media-playback-start at CameraPreview.qml, line 20
WARN qml: QML Image: Cannot open: qrc:/Scanner/media-playback-start at CameraPreview.qml, line 20
CRIT scanner: posted scan 1  ua: "BrickStore/9999.1" at itemscanner.cpp, line 143
CRIT scanner: finished scan 1  status: 200  error: QNetworkReply::NoError at itemscanner.cpp, line 151
CRIT scanner: posted scan 2  ua: "BrickStore/9999.2" at itemscanner.cpp, line 143
CRIT scanner: finished scan 2  status: 200  error: QNetworkReply::NoError at itemscanner.cpp, line 151
CRIT scanner: posted scan 3  ua: "BrickStore/9999.3" at itemscanner.cpp, line 143
CRIT scanner: finished scan 3  status: 200  error: QNetworkReply::NoError at itemscanner.cpp, line 151


I now have a much bigger issue as I can no longer run any version of Brickstore stably. I have even re-installed the current active version and this has the same issue of just closing the application when trying to start a new document.


Any ideas what is going on?

**Comment by rgriebl** [comment] 2024-01-27 11:17
Regarding the original problem: I think I found and fixed the problem. @360er0 could you please check if you still see duplicates for requests with that `9999` version?

Regarding Keith's crash problem: Qt 6.6.1 has a bug that can crash combo-boxes when "Accessibility" options in macOS are enabled. I did make a workaround that currently works for everybody else (according to sentry crash reports). The actual fix will be in the next Qt release that is scheduled for Jan 30th.
In the meantime, please go to your system settings -> Accessibility and disable all the things you can live without for a few days.

**Comment by BrickArena** [comment] 2024-01-27 12:02
Regarding, the new issue its far from ideal but will give it a go. Oddly I turned most off and it works. Then turned them all back on and it continues to work.

Here is what I am seeing in the developer console currently.


CRIT scanner: posted scan 1  ua: "BrickStore/9999.1" at itemscanner.cpp, line 143
CRIT scanner: finished scan 1  status: 200  error: QNetworkReply::NoError at itemscanner.cpp, line 151
CRIT scanner: posted scan 2  ua: "BrickStore/9999.2" at itemscanner.cpp, line 143
CRIT scanner: finished scan 2  status: 200  error: QNetworkReply::NoError at itemscanner.cpp, line 151
CRIT scanner: posted scan 3  ua: "BrickStore/9999.3" at itemscanner.cpp, line 143
CRIT scanner: finished scan 3  status: 200  error: QNetworkReply::NoError at itemscanner.cpp, line 151
CRIT scanner: posted scan 4  ua: "BrickStore/9999.4" at itemscanner.cpp, line 143
CRIT scanner: finished scan 4  status: 200  error: QNetworkReply::NoError at itemscanner.cpp, line 151
CRIT scanner: posted scan 5  ua: "BrickStore/9999.5" at itemscanner.cpp, line 143
CRIT scanner: finished scan 5  status: 200  error: QNetworkReply::NoError at itemscanner.cpp, line 151
CRIT scanner: posted scan 6  ua: "BrickStore/9999.6" at itemscanner.cpp, line 143
CRIT scanner: finished scan 6  status: 200  error: QNetworkReply::NoError at itemscanner.cpp, line 151


BrickStore 2024.1.4 (build: 1166)
brickstore.ldraw: 27 Jan 2024 11:13:04 +0000
brickstore.locale: en
build.arch: arm64
build.compiler: clang 14.0.3 (clang-1403.0.22.14.1)
build.date: 2024-01-27T00:47:14.000
build.host: Mac-1706312914822.local
build.number: 1166
build.qt.version: 6.6.1
hw.cpu: Apple M1 Max
hw.cpu.arch: arm64
hw.gpu: Apple M1 Max
hw.gpu.arch: sppci_vendor_Apple
hw.memory.gb: 32.0
os.arch: arm64
os.productname: macOS 14.2
qt.debug: false
qt.platformname: cocoa
qt.version: 6.6.1





Regards


Keith

**Comment by 360er0** [comment] 2024-01-27 12:19
@rgriebl No, I don't see any duplicates today for requests with the `9999` version. Nice work!

**Closed** 2024-01-27 23:30 UTC

**Comment by rgriebl** [comment] 2024-01-28 19:54
@tritumBj A cleaned-up version of this fix is available here: https://github.com/rgriebl/brickstore/actions/runs/7687817718
Could you please check if the camera preview works with this version? (It shouldn't have stopped working anyway, because I didn't change anything there)
If this version does work, then my plan is release a BrickStore update this week, once Qt 6.6.2 with the accessibility fix for macOS is out.

**Comment by BrickArena** [comment] 2024-01-29 11:57
Just installed and tested and all seems to be working as expected.

Thanks for resolving this issue and for all the hard work you put into Brickstore. It is an amazing tool that I couldn’t live without.


Regards

Keith
Brick Arena

**Comment by tritumBj** [comment] 2024-01-29 12:09
@rgriebl I have installed the latest version. Everything works as expected including the preview. Thx mate! Awesome work.

**Comment by rgriebl** [comment] 2024-01-31 11:06
Bad news: the Qt 6.6.2 release was pushed back 1 week to Feb 7th
Good news: I did manage to sneak in a fix for a harmless, but annoying crash when quitting on macOS :)

**Comment by BrickArena** [comment] 2024-01-31 11:44
Thats disappointing that it was pushed back, its really becoming frustrating with all the random crashing (closing) even with almost everything in accessibility turned off.

However, I appreciate your workaround. I can handle a single crash at quitting rather than the random closures happening currently. When will you be releasing your fix?

**Comment by BrickArena** [comment] 2024-02-11 14:38
Hi, has Qt 6.6.2 been released yet. Any idea how long now for an update? Sent from my iPhoneOn 31 Jan 2024, at 11:44, Keith Bage ***@***.***> wrote:﻿Thats disappointing that it was pushed back, its really becoming frustrating with all the random crashing (closing) even with almost everything in accessibility turned off.However, I appreciate your workaround. I can handle a single crash at quitting rather than the random closures happening currently. When will you be releasing your fix?On 31 Jan 2024, at 11:06, rgriebl ***@***.***> wrote:Bad news: the Qt 6.6.2 release was pushed back 1 week to Feb 7th
Good news: I did manage to sneak in a fix for a harmless, but annoying crash when quitting on macOS :)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
