### ISSUE TITLE
Add Date Added and Date Last Sold columns

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#400] opened 2021-09-10 07:17 UTC
When downloading the inventory in XML these 2 are there, it could be great to have this info in BrickStore in 2 new columns.

**Comment by chiminirc** [comment] 2021-09-14 16:00
This would be beneficial for pricing adjustments.

**Comment by bgrantwilliams** [comment] 2021-11-14 00:16
Very much agree! Adding "Date Added" and "Date Last Sold" would be incredibly helpful!

**Comment by rgriebl** [comment] 2021-12-12 16:20
Implemented and duplicate of  #384

**Closed by rgriebl** 2021-12-12 16:20 UTC
