### ISSUE TITLE
color removed on partout of minifigure torso assembly

### ISSUE THREAD

**Issue by GreatBrickLab** [rgriebl/brickstore#362] opened 2021-05-26 13:29 UTC
When parting out a minifigure torso assembly the torso defaults to no color

**Comment by rgriebl** [comment] 2021-05-26 14:10
Duplicate of #359. Already fixed in the latest dev build (https://github.com/rgriebl/brickstore/actions)

**Closed by rgriebl** 2021-05-26 14:10 UTC
