### ISSUE TITLE
Cant copy to clipboard when updating inventory?

### ISSUE THREAD

**Issue by Brick-Slayer** [rgriebl/brickstore#163] opened 2021-02-04 04:28 UTC
After I download my inventory and change some prices, I want to upload it. So I select all the items and click Export Bricklink Mass Update XML to clipboard and it opens bricklink and I past it in the bottom box and all it will paste is `<INVENTORY/>` ? Am I doing something wrong here?
[edit: just put the XML tag in back-ticks ... otherwise it's not readable]

**Comment by ZZJHONS** [comment] 2021-02-04 10:56
Just tried and is working for me. Downloaded inventory, changed prices and clicked Mass-update.

**Comment by rgriebl** [comment] 2021-02-04 12:10
I can't reproduce it either. Looking at the code, the only way to reset the quantity and price changes is to run `Edit > Reset Differences`.
You can however easily verify what changes will be exported by switching on `View > Difference Mode` and look at the `Qty. Diff` and `Price. Diff` columns.

**Comment by Brick-Slayer** [comment] 2021-02-04 15:07
Ok i was wrong I didnt adjust prices I only changed my cost for some items. I was trying to update the inventory with the new my cost. Is it possible that it doesnt see any price changes since the prices are the same that it is not updating? I will try to post a video of the issue here

**Comment by paramecie** [comment] 2021-02-04 15:11
No need to make a video, it's an old problem, all what isn't Price or Qty (and new lots of course) isn't upDATED.
Hoping Robert will fix this pain.

See #68

**Comment by Brick-Slayer** [comment] 2021-02-04 15:14
> No need to make a video, it's an old problem, all what isn't Price or Qty (and new lots of course) isn't upDATED.
> Hoping Robert will fix this pain.
> 
> See #68

Thank You I will wait till there is a fix and do it manually.

**Comment by rgriebl** [comment] 2021-02-04 15:37
> No need to make a video, it's an old problem, all what isn't Price or Qty (and new lots of course) isn't upDATED.
> Hoping Robert will fix this pain.

If it was just a 'fix', I would have already done it :wink: At least you gave me some ideas now on how to implement it.

**Comment by rgriebl** [comment] 2021-02-04 15:38
Duplicate of #68

**Closed by rgriebl** 2021-02-04 15:38 UTC

**Comment by paramecie** [comment] 2021-02-04 15:40
> If it was just a 'fix', I would have already done it

Sorry... it's only a 15 years old bug.
Devs should never be under so much pressure.
:O)

Arf - thanks Robert, and happy if I could help.

**Comment by paramecie** [comment] 2021-02-04 23:58
I guess now what can be the problem.
You'ld have to keep a duplicate of each initial field value to detect a change, and compare all this (in a big Inventory Shop, it could take a minute...)

But you could set a "dirty" property to each field of a lot. It could be a false flag: if I add a "a" then I remove the "a", the result would be the same as initially, but the flag is set.
In fact, you'ld need to keep both the initial value and the flag, and manage/compare all this :(

One solution I could see would be to when loading/creating the file, for each item (lot):
* build a delimited string merging the text value of all fields, like "I;3001;Brick;N;Red;...;0;...;true"
* then calculate a quick checksum on this string (ex: 222541253)
* keep this checksum in a (hidden) property of the item
That's it.

When upDATING:
* calculate the current checksum for evey item (lot), 
* when you find a different one, this item changed and has to be exported, etc.

A quick CRC is Adler 32 for ex.
