### ISSUE TITLE
Unable to Import BrickLink Order

### ISSUE THREAD

**Issue by paulellery** [rgriebl/brickstore#881] opened 2024-05-01 23:42 UTC
**Describe the bug**
When attempting to import an order a new window is created, but no items are displayed

**To Reproduce**
1. Launch BrickStore
2. File > Import > Bricklink Order
3. Select an order, Click Import

**Expected behavior**
New window opens with all items from the order listed.  

**Screenshots**
![Capture](https://github.com/rgriebl/brickstore/assets/3256455/c751d3fd-b6aa-4060-b76b-2f966a0d2838)

**System information**

### BrickStore 2024.5.1 (build: 1256)

* **brickstore.edition**: desktop
* **brickstore.ldraw**: 01 May 2024 12:06:42 +0100
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930154)
* **build.date**: 2024-04-30T22:56:21.000
* **build.host**: fv-az1457-427
* **build.number**: 1256
* **build.qt.version**: 6.6.3
* **hw.cpu**: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: Intel(R) HD Graphics 520
* **hw.gpu.arch**: intel
* **hw.memory.gb**: 15.9
* **os.arch**: x86_64
* **os.productname**: Windows 10 Version 22H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.6.3
* **windows.tabletmode**: false

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

**Comment by rgriebl** [comment] 2024-05-02 08:45
Duplicate of #877

**Closed by rgriebl** 2024-05-02 08:45 UTC
