### ISSUE TITLE
Error importing mpd files

### ISSUE THREAD

**Issue by snakebyte73** [rgriebl/brickstore#626] opened 2022-11-05 19:16 UTC
When i try to import a .mpd file, Brickstore imports submodels as the ldr (sub) files instead of parting them out.
I have tried testing with adding a 1x1 brick to the main model and created a sublodel with a 2x2 brick
I then added the submodel 2x2 brick to the main model 1x1 brick.
The resultant import gave a list of the following parts in Brickstore:
1 ps 1x1 brick
1 ps submodel.ldr

The right list shoud be:
1 ps 1x1 brick
1 ps 2x2 brick

I am running on version 2022.10.2
On Windows 11 Version 22H2

**Comment by rgriebl** [comment] 2022-11-05 19:26
Duplicate of #619 
Already fixed and will be in the next release.

**Closed by rgriebl** 2022-11-05 19:26 UTC
