### ISSUE TITLE
Print Template conversion

### ISSUE THREAD

**Issue by nicobubulle** [rgriebl/brickstore#451] opened 2021-11-20 18:36 UTC
Hello,

I tried to figure out a way to convert a print template from *.qs format to *.bs.qml, but it's seems it as to be done by hand. Any chance to have help with this one ?

[Price_grid_byColor.qs.txt](https://github.com/rgriebl/brickstore/files/7575044/Price_grid_byColor.qs.txt)

It is using label template from Allan Smith. I use it to check inventory in one page :
![image](https://user-images.githubusercontent.com/3463842/142737399-0699a1b3-a767-4e8a-897d-29ed039d98e0.png)

Thank you,

Nicolas

**Comment by beaverbrick** [comment] 2021-12-13 23:24
I'm just in the process of converting this document at the moment.
I've done the bulk of it, just got one last section to go through.

I'll post the new file here for you to test when it's ready.  Should be in the next day or so.

**Comment by rgriebl** [comment] 2021-12-14 00:13
@beaverbrick I've started to work on some API docs. It's probably full of typos and copy&paste errors right now, plus it's still missing the `Page`, `Job` and `Script` types. But hey -- it's a start :)

**Comment by rgriebl** [comment] 2021-12-14 00:13
Would have helped to paste the link: https://rgriebl.github.io/brickstore/apidocs/

**Comment by nicobubulle** [comment] 2021-12-14 08:23
Hello,

@beaverbrick @rgriebl Thank you both of you for your work !

Have a nice day,

Nicolas

**Comment by beaverbrick** [comment] 2021-12-14 21:29
@nicobubulle

Here's your price grid for you to try.
Check this page for where to save the file to... https://github.com/rgriebl/brickstore/tree/master/extensions
And remember to remove the .txt file extension from the file also.

Any problems just give me a shout.

[Price_Grid_byColor.bs.qml.txt](https://github.com/rgriebl/brickstore/files/7714864/Price_Grid_byColor.bs.qml.txt)

**Comment by beaverbrick** [comment] 2021-12-15 12:08
@rgriebl 

Thanks Robert, it's a good start and i found it helpful :)
One issue I just can't seem to resolve in the print script is 'printing only the selected lots'.

If I use 'lots', it prints everything in the document, regardless of what is selected.
I've tried using 'doc.lots' but that doesn't seem to contain the data (I could be using it wrong of course).

Don't suppose you have a working example of a print script that prints only those selected?

Thanks :)

**Comment by rgriebl** [comment] 2021-12-15 17:45
There's obviously some code missing to actually implement "selection only" printing... don't ask me why I never noticed that ;)
Shouldn't be a big deal though

**Comment by nicobubulle** [comment] 2021-12-15 19:23
@beaverbrick

Thank you, it's working exactly like I need. I hope you don't spend too much time. I'm sure it will be useful for other users who want to print labels.

By the way @rgriebl , is it possible to get the number of items in a set has a comment or remark. I would like to print labels for mine with this info.

Thank you,

Nicolas

**Comment by rgriebl** [comment] 2021-12-15 20:52
It's plain JavaScript ... pick your poison :)
```
        let count1 = 0
        lots.forEach(lot => { if (lot.remarks != '') ++count1 })

        let count2 = lots.filter(lot => lot.remarks != "").length
        let count3 = 0
        for (let lot of lots) {
            if (lot.remarks !== '')
                ++count3
        }
        console.log("Lots with remarks: " + count1 + " " + count2 + " " + count3)
```

**Comment by beaverbrick** [comment] 2021-12-17 19:08
@rgriebl 

> One issue I just can't seem to resolve in the print script is 'printing only the selected lots'.
> 
> If I use 'lots', it prints everything in the document, regardless of what is selected. I've tried using 'doc.lots' but that doesn't seem to contain the data (I could be using it wrong of course).

is this fixed in...
Log https://github.com/rgriebl/brickstore/issues/482
Commit https://github.com/rgriebl/brickstore/commit/1d9d3c9325a840c57936fb54826729248ad34640
?

Thanks :)

**Comment by rgriebl** [comment] 2021-12-17 21:06
Yes it is

**Comment by rgriebl** [comment] 2021-12-17 21:24
BTW: the docs should be fairly complete now when it comes to printing extensions:
https://rgriebl.github.io/brickstore/extensions/

**Comment by beaverbrick** [comment] 2021-12-17 21:56
Thank you, I'll give it a test :)

**Comment by beaverbrick** [comment] 2021-12-17 22:59
Given it a test and there seems to be a little bug... if the print script hits a 'return' command, BrickStore closes.
A blank dialog box appears very briefly, before BrickStore closes (see pic 1).

I'm using Version 2021.11.1 (build: 564).
To reproduce... simply use the 'Extras - Print: Classic Layout' on a blank document (so it hits the 'return' at the start of the script).
Using File - Print on a blank document, does nothing,

And also can I ask for a little change too please... when a lot(s) has been selected, can the print dialog box default to 'Selection Only' (see pic 2)... otherwise you have to change it every time.

Thanks v much :)

![BrickStore_Quits](https://user-images.githubusercontent.com/81053064/146616455-cfa51fed-5057-48a5-947e-5854fd24534f.png)
.

![BrickStore_Selection_Only](https://user-images.githubusercontent.com/81053064/146616724-e5095e13-5d2d-41ac-bcab-519171170548.png)

**Comment by nicobubulle** [comment] 2021-12-24 09:22
@rgriebl Maybe we can close this issue ? The template works fine for me. You can add it to git. Thank you

**Closed** 2022-01-10 20:27 UTC
