### ISSUE TITLE
Difference Mode active not saved with layout.

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#137] opened 2021-01-27 13:38 UTC
As the tittle says, if you save the layout as the user uno (empty name) with the Difference mode active, it is not saved, when opening a new file is not active.

If you save the layout with a name and open a file and apply it, it is also not active.

BTW the columns positions are saved correctly.

**Comment by paramecie** [comment] 2021-01-27 15:26
First: is this mode a Layout to be saved in the document?
Same question for View/Show Input Errors?

**Comment by rgriebl** [comment] 2021-01-27 15:31
"Difference Mode" is separate from the column layout (as is "Simple Mode" and "Show Input Errors")

**Comment by rgriebl** [comment] 2021-01-31 12:44
Closing for now, as it works as intended. I know that the inter-dependencies between column layout, diff mode and simple mode are quite complex, but I cannot think of another way that would be more intuitive for everybody

**Closed by rgriebl** 2021-01-31 12:44 UTC
