### ISSUE TITLE
can't open 2022.9.1 on Mac OS 12.5 or 12.6

### ISSUE THREAD

**Issue by jaamrode** [rgriebl/brickstore#585] opened 2022-09-14 15:40 UTC
I can't open Brickstore app any more after update.  Here is the crash report.

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               BrickStore [3217]
Path:                  /Applications/BrickStore.app/Contents/MacOS/BrickStore
Identifier:            de.brickforge.brickstore
Version:               2022.9.1 (767)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-09-14 09:39:32.6845 -0600
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Anonymous UUID:        7F1CF5A2-9982-41E9-3BAD-2CE3E37BC69A

Sleep/Wake UUID:       4C4F78E4-BAA8-4EA0-A55B-982C108CA318

Time Awake Since Boot: 2200 seconds
Time Since Wake:       1213 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '@rpath/QtQuickControls2Impl.framework/Versions/A/QtQuickControls2Impl'
Referenced from: '/Applications/BrickStore.app/Contents/MacOS/BrickStore'
Reason: tried: '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x103363e98 __abort_with_payload + 8
1   dyld                          	       0x10336b024 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x10336b058 abort_with_payload + 16
3   dyld                          	       0x103322a28 dyld4::halt(char const*) + 580
4   dyld                          	       0x10331dfb8 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3644
5   dyld                          	       0x10331d06c start + 488

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016d942a08   x3: 0x0000000000000091
    x4: 0x000000016d942608   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x00000000000002e0
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x000000016d942678  x11: 0x00000000000000a6
   x12: 0x0000000000000000  x13: 0x0000000000000033  x14: 0x000000024d7754f6  x15: 0x0000000000000000
   x16: 0x0000000000000209  x17: 0x000000010331b14c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016d942608  x21: 0x0000000000000091  x22: 0x000000016d942a08  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x000000016d942608  x26: 0x0000000000000400  x27: 0x0000000000000355
   x28: 0x000000000000011f   fp: 0x000000016d9425d0   lr: 0x000000010336b024
    sp: 0x000000016d942590   pc: 0x0000000103363e98 cpsr: 0x00001000
   far: 0x0000000103194000  esr: 0x56000080  Address size fault

Binary Images:
       0x103318000 -        0x103377fff dyld (*) <38ee9fe9-b66d-3066-8c5c-6ddf0d6944c6> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=12.2M resident=0K(0%) swapped_out_or_unallocated=12.2M(100%)
Writable regions: Total=9216K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9216K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__DATA                              80K        2 
__DATA_CONST                       272K        2 
__LINKEDIT                        3616K        2 
__TEXT                            8864K        2 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                             77.5M       12 

-----------
Full Report
-----------

{"app_name":"BrickStore","timestamp":"2022-09-14 09:39:32.00 -0600","app_version":"2022.9.1","slice_uuid":"f74543d9-f30e-34ad-8f8f-dd07386d712e","build_version":"767","platform":1,"bundleID":"de.brickforge.brickstore","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6 (21G115)","incident_id":"866723B9-7E07-43E2-A791-3593FC23E0A6","name":"BrickStore"}
{
  "uptime" : 2200,
  "procLaunch" : "2022-09-14 09:39:32.6621 -0600",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "procStartAbsTime" : 53591696095,
  "coalitionID" : 2264,
  "osVersion" : {
    "train" : "macOS 12.6",
    "build" : "21G115",
    "releaseType" : "User"
  },
  "captureTime" : "2022-09-14 09:39:32.6845 -0600",
  "incident" : "866723B9-7E07-43E2-A791-3593FC23E0A6",
  "bug_type" : "309",
  "pid" : 3217,
  "procExitAbsTime" : 53592217687,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "BrickStore",
  "procPath" : "\/Applications\/BrickStore.app\/Contents\/MacOS\/BrickStore",
  "bundleInfo" : {"CFBundleShortVersionString":"2022.9.1","CFBundleVersion":"767","CFBundleIdentifier":"de.brickforge.brickstore"},
  "storeInfo" : {"deviceIdentifierForVendor":"AAF6C4C6-C0D8-50BB-A633-C3B3E2F55BBB","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "de.brickforge.brickstore",
  "crashReporterKey" : "7F1CF5A2-9982-41E9-3BAD-2CE3E37BC69A",
  "wakeTime" : 1213,
  "sleepWakeUUID" : "4C4F78E4-BAA8-4EA0-A55B-982C108CA318",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: '@rpath\/QtQuickControls2Impl.framework\/Versions\/A\/QtQuickControls2Impl'","Referenced from: '\/Applications\/BrickStore.app\/Contents\/MacOS\/BrickStore'","Reason: tried: '' (no such file), '' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":39118,"threadState":{"x":[{"value":6},{"value":1},{"value":6133393928},{"value":145},{"value":6133392904},{"value":0},{"value":0},{"value":736},{"value":32},{"value":9},{"value":6133393016},{"value":166},{"value":0},{"value":51},{"value":9889600758},{"value":0},{"value":521},{"value":4348555596,"symbolLocation":392,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6133392904},{"value":145},{"value":6133393928},{"value":1},{"value":6},{"value":6133392904},{"value":1024},{"value":853},{"value":287}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4348882980},"cpsr":{"value":4096},"fp":{"value":6133392848},"sp":{"value":6133392784},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4348853912,"matchesCrashFrame":1},"far":{"value":4346953728}},"frames":[{"imageOffset":310936,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":0},{"imageOffset":340004,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":0},{"imageOffset":340056,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":0},{"imageOffset":43560,"symbol":"dyld4::halt(char const*)","symbolLocation":580,"imageIndex":0},{"imageOffset":24504,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3644,"imageIndex":0},{"imageOffset":20588,"symbol":"start","symbolLocation":488,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4348542976,
    "size" : 393216,
    "uuid" : "38ee9fe9-b66d-3066-8c5c-6ddf0d6944c6",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 6803587072,
  "size" : 3144744960,
  "uuid" : "049b583e-d4dc-3b2b-88da-e52d6e18313d"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=12.2M resident=0K(0%) swapped_out_or_unallocated=12.2M(100%)\nWritable regions: Total=9216K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9216K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__DATA                              80K        2 \n__DATA_CONST                       272K        2 \n__LINKEDIT                        3616K        2 \n__TEXT                            8864K        2 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                             77.5M       12 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "61301e3a61217b3110231469",
      "factorPackIds" : {
        "SIRI_FIND_MY_CONFIGURATION_FILES" : "6216ae152a40e71046e16225"
      },
      "deploymentId" : 240000016
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000468
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by rgriebl** [comment] 2022-09-14 15:43
Duplicate of #583
It's already fixed and a new release will be created shortly.

**Closed by rgriebl** 2022-09-14 15:43 UTC

**Comment by BricksNW** [comment] 2022-09-14 18:57
When will this release be issued please- now ground to complete halt with 12 part complete box files that cut be accessed
