### ISSUE TITLE
Dropdown menu appearing on other monitor on dual monitor set up

### ISSUE THREAD

**Issue by jclee100** [rgriebl/brickstore#797] opened 2023-11-27 10:30 UTC
**Describe the bug**
On a dual monitor setup, drop down menu appears on a separate monitor.

**To Reproduce**
1. Have a dual monitor set up
2. Open application
3. Move application to the other monitor
4. Click on any dropdown menu such as File

**Expected behavior**
Menu should appear below the menu bar

**Screenshots**

**System information**
BrickStore 2023.11.2 (build: 1093)
brickstore.ldraw: 24 Nov 2023 18:14:43 +0800
brickstore.locale: en
build.arch: x86_64
build.compiler: Microsoft Visual-C++2019 (192930152)
build.date: 2023-11-14T02:11:09.000
build.host: fv-az1457-229
build.number: 1093
build.qt.version: 6.5.2
hw.cpu: AMD Ryzen 5 5600X 6-Core Processor
hw.cpu.arch: x86_64
hw.gpu: NVIDIA GeForce RTX 3060 Ti
hw.gpu.arch: nvidia
hw.memory.gb: 31.9
os.arch: x86_64
os.productname: Windows 10 Version 22H2
qt.debug: false
qt.platformname: windows
qt.version: 6.5.2
windows.tabletmode: false

**Comment by rgriebl** [comment] 2023-11-27 10:37
Duplicate of #794

**Closed by rgriebl** 2023-11-27 10:37 UTC
