### ISSUE TITLE
Impossible to add new Set

### ISSUE THREAD

**Issue by Yomeno** [rgriebl/brickstore#707] opened 2023-04-10 16:01 UTC
When I ant to add a Set I can't add because the color column are disabled and it's required to chose a color (even if "not applicable") to add the set in the listing.
On Mac, version 2023.4.1 build 996

**Comment by rgriebl** [comment] 2023-04-10 16:22
Duplicate of #703

**Closed by rgriebl** 2023-04-10 16:22 UTC
