### ISSUE TITLE
Update won’t work on Mac OS 

### ISSUE THREAD

**Issue by BricksNW** [rgriebl/brickstore#618] opened 2022-10-18 09:11 UTC
Just like the previous release the update crashes. Is this a known problem?

**Comment by rgriebl** [comment] 2022-10-18 09:32
Seems like Apple broke support for macOS 10.14 with their latest 13.1 SDK update: https://developer.apple.com/forums/thread/694260

Which versions do run on your machine and which crash? Maybe I can find a working SDK version from the build logs and downgrade to that version to workaround this issue until Apple fixes it.

**Comment by BricksNW** [comment] 2022-10-19 07:42
Thank you. I have deleted the new version and put the previous one back on

**Comment by rgriebl** [comment] 2022-10-19 11:02
And which one is it that you put back? 9.2/9.3? or even older, 4.1?
As far as I know, only 9.1 was broken on all macOSes (due to a faulty package generated by the build server).

**Comment by BricksNW** [comment] 2022-10-19 11:15
Hi Robert, it is Version 2022.10.1 (build 808)


Sent from Yahoo Mail for iPhone


On Wednesday, October 19, 2022, 12:02 pm, rgriebl ***@***.***> wrote:




And which one is it that you put back? 9.2/9.3? or even older, 4.1?
As far as I know, only 9.1 was broken on all macOSes (due to a faulty package generated by the build server).

**Comment by BricksNW** [comment] 2022-10-19 11:16
Sort, build 803


Sent from Yahoo Mail for iPhone


On Wednesday, October 19, 2022, 12:15 pm, steve brown ***@***.***> wrote:

Hi Robert, it is Version 2022.10.1 (build 808)


Sent from Yahoo Mail for iPhone


On Wednesday, October 19, 2022, 12:02 pm, rgriebl ***@***.***> wrote:




And which one is it that you put back? 9.2/9.3? or even older, 4.1?
As far as I know, only 9.1 was broken on all macOSes (due to a faulty package generated by the build server).

**Comment by rgriebl** [comment] 2022-10-23 14:46
Looking at this again, I just saw that the sentry crash was from a `2022.4.1` version. I didn't notice that before, because it came right in before you opened the bug report and it was for macOS 10.14 (which is rare enough nowadays) so I thought, THIS must be the crash.

Could you please double-check that you didn't accidentally install an old 4.1 version?

If that still doesn't work, could you also try a current dev build from here https://github.com/rgriebl/brickstore/actions/runs/3293757219 (you need to be logged into GitHub to download)?

This is really weird, because BrickStore didn't change anything between 10.1 and 10.2 that would explain this problem and also the GitHub CI did not get an Apple XCode/SDK between these two versions.

**Comment by rgriebl** [comment] 2022-11-10 12:13
Any news? Did you by chance try the new `2022.11.1`?

**Comment by BricksNW** [comment] 2022-11-16 09:46
Hi Robert. I have downloaded the new version but kept the old be as well. All seems to ge Kay, but to be fair I haven’t used it much since as I am in the process of sorting a it of bulk out a the moment. I will keep my eye on it and see how it worksKind regards Steve BrownOn 10 Nov 2022, at 12:13, rgriebl ***@***.***> wrote:﻿
Any news? Did you by chance try the new 2022.11.1?

**Comment by rgriebl** [comment] 2022-12-06 18:40
Closing for now as not reproducible. Please re-open if this happens again.

**Closed by rgriebl** 2022-12-06 18:40 UTC
