### ISSUE TITLE
Many times the import shopping cart features shows no results until restarting the application.

### ISSUE THREAD

**Issue by chiminirc** [rgriebl/brickstore#453] opened 2021-11-24 01:44 UTC
I'll be using brickstore and have it open. I go to import a cart and the import dialog popup will come up.  The button to refresh works.  The status will show "last updated right now". There is nothing in the list.

Close brickstore, go to import the cart again, last status shows a recent update but results are still empty. I hit the refresh icon again and this time I get the results.

This is somewhat repeatable.

**Comment by rgriebl** [comment] 2021-12-19 17:16
Duplicate of #485

**Closed by rgriebl** 2021-12-19 17:16 UTC
