### ISSUE TITLE
quantity 

### ISSUE THREAD

**Issue by honu321** [rgriebl/brickstore#793] opened 2023-11-15 14:26 UTC
**Describe the bug**
A clear description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information**
Please tell us which system you are running on and which BrickStore version you are using.
In BrickStore, just open `Help` > `System information...`, Click `Copy to clipboard` and then paste  here.

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

**Comment by rgriebl** [comment] 2023-11-16 00:05
Closing -- Just the word 'quantity' is not a bug report

**Closed by rgriebl** 2023-11-16 00:05 UTC
