### ISSUE TITLE
Crashes on MacOS Ventura 13.2.1 (BrickStore 2023.5.1 (build: 1049))

### ISSUE THREAD

**Issue by saosivert** [rgriebl/brickstore#738] opened 2023-06-03 20:59 UTC
Crashes when 

1. opening bsx file
2. saving bsx file
3. adding parts to file
etc

Not crashing when on welcome screen

Haven't experienced crashes on previous version of BrickStore

**Comment by rgriebl** [comment] 2023-06-03 21:21
Duplicate of #736 

This is an unfortunate combination of macOS 13 + Qt 6.5.1 (the library BrickStore is built upon) + Accessibility options being enabled on your system (e.g. Voice Over).
I thought I had a workaround, but it doesn't work 100%. I'm currently experimenting with an manually patched version for macOS until the next Qt 6.5.2 update is out (this will be August).
Going back to Qt 6.5.0 is also not an option for everybody, because a few web cams are not working correctly there.
If you didn't have problems with non-working webcams before, then please just use an older version of BrickStore for the time being.

**Comment by Yomeno** [comment] 2023-07-09 19:17
Same problem here. So, waiting for august :)

**Comment by rgriebl** [comment] 2023-09-22 21:46
Fixed with release 2023.8.1, which is based on Qt 6.5.2

**Closed by rgriebl** 2023-09-22 21:46 UTC
