### ISSUE TITLE
Win 10 Intel version 2024.12.2 - will not run

### ISSUE THREAD

**Issue by tallytoyBL** [rgriebl/brickstore#929] opened 2024-12-10 08:13 UTC
**Describe the bug**
Previous version did not run. Saw on my other PC (Win 11) there was an update. Downloaded 2024.12.2 with the same result - BrickStore does not run. After installation, with check box selected to run, complete installation and nothing happens.

**To Reproduce**
1. Double click on icon
or
2. Right click on Program and select "run as administrator"

**Expected behavior**
Program should start - nothing happens

**System information**
BrickStore version:  2024.12.2

PC
Processor	Intel(R) Core(TM) i5-6600T CPU @ 2.70GHz   2.71 GHz
Installed RAM	8.00 GB (7.89 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 10 Pro
Version	22H2
OS build	19045.5131

**Comment by judamPL** [comment] 2024-12-10 08:36
At my place, on several computers also does not start. Even the old version.

**Comment by judamPL** [comment] 2024-12-10 09:44
> Did you try to restart your PCs?

YES :-)

I have already tried to reinstall the program from scratch. And it doesn't work. But I installed version 20024.5.2 and it works fine. 
The new versions will not start.

**Comment by rgriebl** [comment] 2024-12-10 10:36
I cannot reproduce this issue anymore, because once the correct Microsoft C++ libs are installed (and found), it will just work.
The biggest problem though is that the Sentry.io crash reports have been flooded by this stupid issue and open-source projects only have a limited number of reports available per month ... that means I currently only see THAT is crashes, but I cannot get to the details of your recent crashes.

Could you please test something for me? I have a test build cooking right now: https://github.com/rgriebl/brickstore/actions/runs/12254209809
It should be done in around 20 min. Could you please try to install and run this one? You have to be logged in to GitHub to download and the download is then a ZIPed installer , don't ask why ... it's a Microsoft thing ;)

**Comment by judamPL** [comment] 2024-12-10 10:47
I checked on 4 computers.
Two new computers from 2023 and 2024 year of production, with Windows 11 - The program works in any version, even the latest. 

An old computer about 10 years old, windows 10
Only version 2024.5.2 works - Newer versions no longer work

Old computer about 10 years old - installed windows 11 test mode (forced installation) 
Only version 2024.5.2 works - Newer ones no longer work


If you need, I can give you access to one of my old  computers,  via Anydesk.  You can write to me on whatsapp +48508434110 I will give you login and password to the computer.

**Comment by judamPL** [comment] 2024-12-10 11:07
I installed the version from the link zip file. It appeared as 12.2 -- But it still doesn't work. It won't boot.

**Comment by tallytoyBL** [comment] 2024-12-10 23:02
Went back and installed version 2024.5.2 which works fine.
I'll keep an eye out for an update or if you need any testing done.
Thanks

**Comment by rgriebl** [comment] 2024-12-15 20:33
I think I finally found the reason why this happening on some machines: it's - again - Microsoft's fault:
I guess that all of you having this problem have OneDrive installed?
OneDrive injects it's Explorer Shell extension into the BrickStore process and also changes the library import path to point to it's own library folder. So when BrickStore wants to load `MSVCP140.dll` it will be redirected to `C:\Users\<user>\AppData\Local\Microsoft\OneDrive\<version>\` and loads an old, broken version from there instead of the freshly installed, fixed on from `C:\Windows\System`
OneDrive is one of the first things getting disabled on my machines, so that's why I had a hard time debugging this.
I haven't found a workaround yet: it's either disabling OneDrive (https://www.oo-software.com/shutup10 is your friend) or running an old build of BrickStore (MS broke the MSVCP140.dll around June 2024, so that's why BrickStore 2024.5.2 still works)

**Comment by rgriebl** [comment] 2024-12-16 01:47
Could you please test another `Windows-x64` build from here as well? https://github.com/rgriebl/brickstore/actions/runs/12335262306

**Comment by judamPL** [comment] 2024-12-16 10:30
:-( not started

**Closed** 2024-12-16 16:19 UTC

**Comment by rgriebl** [comment] 2024-12-16 16:43
Thanks for all the testing. I have now managed to somewhat reproduce this here and THIS build fixes the problem for me:
https://github.com/rgriebl/brickstore/actions/runs/12356821002
Would be nice if you could give it a try as well

**Comment by rgriebl** [comment] 2024-12-17 20:35
@tallytoyBL @judamPL I'd like to release a fixed version soon, but I would need someone with the actual problem to verify if it works

**Comment by judamPL** [comment] 2024-12-17 21:22
Yes, I confirm, everything is fine now.  I installed it on 3 different old computers and it works fine on each of them.

**Comment by tallytoyBL** [comment] 2024-12-18 22:47
Everything is working with the new update - Thank You
