### ISSUE TITLE
User default layout sort not working correctly when importing inventory

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#201] opened 2021-02-14 11:25 UTC
![image](https://user-images.githubusercontent.com/1063368/107875309-7ecb6580-6ebf-11eb-9e17-4aad008e6d54.png)

![image](https://user-images.githubusercontent.com/1063368/107875323-8559dd00-6ebf-11eb-9b0a-0ce4d925bc45.png)

PD: sorting manually again corrects it

**Comment by rgriebl** [comment] 2021-02-14 11:43
This is a duplicate of #39, but we didn't have user configurable Lay-outs back then.

**Closed** 2021-02-14 12:04 UTC
