### ISSUE TITLE
Download and Decompress Failure

### ISSUE THREAD

**Issue by Lemons222** [rgriebl/brickstore#814] opened 2024-01-16 21:04 UTC
Hello there,

I installed the recent update, the previous update was working fine. Now I receive "Could not load the new database, download and decompress failed, connection timed out" error.

I'm unsure how to fix it.

Is it possible to install a previous version?

Many thanks

**Comment by rgriebl** [comment] 2024-01-16 22:03
Duplicate of #813 
This is a temporary routing failure in a datacenter - a previous version won't help.

**Closed by rgriebl** 2024-01-16 22:03 UTC
