### ISSUE TITLE
Visual C++ runtime DLL's missing after installation

### ISSUE THREAD

**Issue by SteveTheBrick** [rgriebl/brickstore#371] opened 2021-06-07 18:12 UTC
A couple of times recently I've installed the latest Brickstore version, it asks to restart my computer and then it won't run because of missing VC++ dll's.

I'm surprised no-one else has reported this, so maybe it's just something wrong with my system (Win10).

Running the VC redistributable from MS and choosing 'repair' has fixed the problem both times.

**Comment by rgriebl** [comment] 2021-06-07 18:36
Those VC Runtimes are mini-Windows updates nowadays. Sometime you do get away with not rebooting, but sometimes you have to reboot.
Nobody else seems to have problems with the runtime missing after a reboot though.

**Comment by SteveTheBrick** [comment] 2021-06-07 18:51
If nobody else is having the problem I guess I've just got a slight problem with my Windows installation. Please feel free to close the issue.

**Comment by rgriebl** [comment] 2021-06-07 19:00
Did you reboot and still have the problem? That part is unclear in your bug report.

**Comment by SteveTheBrick** [comment] 2021-06-07 19:08
Yes. The installer asked to do a reboot and I clicked on 'yes, restart now'. After the reboot I tried to run Brickstore and it complained of the missing dll's. The redistributable fixed the problem without a futher reboot.

**Comment by ZZJHONS** [comment] 2021-06-07 20:31
Only one of the latest updates asked me to restart the computer, but I didn't do it and BrickStore worked fine.

**Comment by rgriebl** [comment] 2021-06-22 21:03
I'm closing this now, because I cannot reproduce it and nobody else seems to have this problem.
Something is wrong with your Windows installation, if it doesn't cleanly update the MSVC runtimes when triggered from the BrickStore installer. Plus I couldn't do anything either: those runtime packages are black boxes from Microsoft that you just have to install alongside your app.

**Closed by rgriebl** 2021-06-22 21:03 UTC

**Comment by SteveTheBrick** [comment] 2021-06-22 21:16
No problem, Robert, it does indeed look like a problem with my Windows installation.
