### ISSUE TITLE
Reverse color search???

### ISSUE THREAD

**Issue by GreatBrickLab** [rgriebl/brickstore#164] opened 2021-02-05 14:42 UTC
Is it possible to select a specific color then filter by a category for all parts only that come in that color and that category?    Additionally,  if you could search a word,  like "horn" and then say only match those that come in a specific color.  That could speed up finding parts a lot.   For the horn example I have part 89522 (horn)   I type in horn and then I know the color to be pearl gold.   So I say show me all horn and that have a known color of pearl gold.

**Comment by paramecie** [comment] 2021-02-05 18:41
Implies "Known Colors" to work reliably enough - which isn't unfortunately.
See #94

**Comment by GreatBrickLab** [comment] 2021-02-05 19:07
I have seen that also.   For those parts that it does work it would be nice.  One simple example that I ran into recently on many animals. Parrot, snake and some other no pattern ones. You have to go to the all colors lost to pick dark grey.   Even with having to do all that.  Using the new brick store is so much better. Thank goodness is it getting work again.  And it is free!   Amazing!!!!

**Comment by paramecie** [comment] 2021-02-06 02:43
> For those parts that it does work it would be nice.

Not parts only, but combinations also.
So a LEGO code for this part in Light Bluish Gray may exist, but not in Red color.
You'd then see an incomplere "Known Colors" for this part, WITHOUT BrickStore (and you) being able to tell if it's complete or not.

**Comment by rgriebl** [comment] 2021-02-11 23:15
Duplicate of #94

**Closed by rgriebl** 2021-02-11 23:15 UTC
