### ISSUE TITLE
Cursor has changed

### ISSUE THREAD

**Issue by Dhomal** [rgriebl/brickstore#781] opened 2023-10-12 01:54 UTC
**Describe the bug**
The cursor changes to a blue spinning doughnut shape. Otherwise, operation seems unaffected. Also, the cursor seems to only be changed when in/over a BS area. It remains normal in other uses.

**To Reproduce**
I have no idea how this has happened, but it is now on 2 of the 4 laptops I use with BS>

**Expected behavior**
Cursor should remain the same

**System information**
### BrickStore 2023.8.1 (build: 1059)

* **brickstore.ldraw**: 03 Oct 2023 16:01:58 -0400
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: Microsoft Visual-C++2019 (192930151)
* **build.date**: 2023-08-12T14:25:40.000
* **build.host**: fv-az1237-625
* **build.number**: 1059
* **build.qt.version**: 6.5.2
* **hw.cpu**: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: Intel(R) UHD Graphics 630
* **hw.gpu.arch**: intel
* **hw.memory.gb**: 63.9
* **os.arch**: x86_64
* **os.productname**: Windows 10 Version 22H2
* **qt.debug**: false
* **qt.platformname**: windows
* **qt.version**: 6.5.2
* **windows.tabletmode**: false

The other laptop is different from this one however.

**Comment by rgriebl** [comment] 2023-11-13 20:59
I couldn't reproduce that, but I found and fixed some very old code that might have been responsible.
Can you still trigger this behavior with 2023.11.x?

**Comment by Dhomal** [comment] 2023-11-14 05:43
Hello-

Thanks for getting back to me. Apparently after some point, it went away,
and honestly, I just did not think about it as it was not in my face as the
odd rotating circle thing.

Perhaps it Was that old code that you fixed!

Thanks though for thinking to reach out to me about it!

-Doug Raas

**Comment by rgriebl** [comment] 2023-11-16 00:13
Closing - please reopen if it still happens

**Closed by rgriebl** 2023-11-16 00:13 UTC
