### ISSUE TITLE
the application freezes after update

### ISSUE THREAD

**Issue by teddywsb** [rgriebl/brickstore#686] opened 2023-03-09 15:22 UTC
After instaling latest version on windows 11 it not working. the application freezes

I uninstall it and find older version, but then windows defender report virus trojan

**Comment by bricksbytheriver** [comment] 2023-03-09 20:51
Brickstore app is freezing on windows 10 today. Any suggestions to solve this issue?
Thanks in advance,

**Comment by HarkonS** [comment] 2023-03-10 10:20
I seem to have the same problem (on Win 10), but can confirm that the issue happens when the program tries to open my main data file with ~364 k parts in 6,9 k lots.
Once I rename that file the program opens fine and also loads all the other files I have always open.
What is funny is that I then cannot even open an older version of that file which I know worked fine without any problems (in this case from roughly 3 months ago with ~325 k parts and 6,6 k lots).
And even more strange is that when reverting to an older program version (Windows-x64-BrickStore-2022.11.2) the same problems (neither the newest nor an older version of the data file will load) persist.

So it seems that the problem is not within the program itself but some other circumstances that have changed and persist through deinstallation.

**Comment by teddywsb** [comment] 2023-03-10 21:27
i try today one more time, still the same situation. maybe someone have pervous version and can send me to my email?

**Comment by rgriebl** [comment] 2023-03-11 00:38
Any time someone reports BrickStore to "freeze" in the past, it was their firewall/antivirus blocking the process for whatever reason. Please disable your anti-virus and try again. Check your `C:\Program Files\BrickStore\BrickStore.exe` on virustotal.com first for peace of mind. The official download here from github is clean though.

**Comment by bricksbytheriver** [comment] 2023-03-11 07:42
Hello again,
My PC made the needed Windows (10) updates and BrickStore is finally working well!

**Comment by teddywsb** [comment] 2023-03-11 07:51
> 

i only have windows defender. beetween older and new version of brickstore i do not install any other antywirus software or windows updates. Now i do not have any updates to install and after reinstal brickstore it's still freeze in blanc window

**Comment by HarkonS** [comment] 2023-03-11 10:02
Alright, I was able to fix it.
I searched for any remnants of the program after uninstalling and came across C:\Users\[User]\AppData\Local\BrickStore\cache which still contained more than 1.4 GiB of data. After renaming that folder and reinstalling the program I was able to open all my files fine.

It has to be noted that this is not the only data that remains after an uninstall, as after reinstalling, BrickStore still opened all files that were loaded before the uninstall.

Some more info about the state before renaming/deleting the cache folder: I was able to open all my files up to 3.075 KB, but none that are 3.150 KB or larger.

Just for completeness sake: Win 10 showed no available updates. Only using Windows Defender and disbaling that momentarily did not change anything. Virustotal also found nothing.

**Comment by teddywsb** [comment] 2023-03-11 10:15
i confirm that when i delete folder from local data and install one more time it's working. so i close topic.

**Comment by rgriebl** [comment] 2023-03-11 12:06
Reopening, since this seems to be more than just the typical Anti-virus freeze.
@HarkonS please don't delete the cache folder yet, as that is currently our only lead towards the root cause of the problem. Would it be ok for you to ZIP up that diectory and upload it for me? There is no personal data in that directory - it'll just be one big upload...). Please send me an email (click my name) and I'll give you a personal upload URL.

**Comment by rgriebl** [comment] 2023-03-11 13:32
Thanks to HarkonS' cache data, I could reproduce the freeze. It seems there is invalid data in the BrickLink Item ChangeLog, leading to infinite loops.
The example I ran into is `72206` being renamed to `72206c01`, but then also `72206c01` being renamed to `72206`, creating a nice infinite loop. 
I need to dig deeper what is causing these weird changelog loops: BrickLink sending wrong data or BrickStore interpreting it wrongly...

**Comment by rgriebl** [comment] 2023-03-11 14:45
Found it -- `72206c01` has been renamed twice in its lifetime, but BrickStore is only looking at the older rename (which really is the number swap described above, sending BrickStore into an infinte loop) instead of the newer one to `72206pb01`. Still unsure if I can fix it with a DB update or if a new BrickStore version is needed.

**Comment by HarkonS** [comment] 2023-03-11 16:50
Thank you for your work!

**Comment by teddywsb** [comment] 2023-03-11 22:40
Thank you so much

**Comment by rgriebl** [comment] 2023-03-14 12:12
The bad news: sadly, this cannot be fixed by a simple database update. 
The good news: after having to re-write the changelog code for the next BrickStore release, all changes are now tracked correctly, no matter how old the file you are loading actually is.

**Closed** 2023-03-14 16:55 UTC
