### ISSUE TITLE
Brickstore Item ID column not working correctly

### ISSUE THREAD

**Issue by Johnersis** [rgriebl/brickstore#876] opened 2024-04-29 18:52 UTC
**Describe the bug**
A clear description of what the bug is.

When trying to order the Inventory by Item ID the inventory returns a non-contiguous range of items
 
**To Reproduce**

Click on Item ID and observe behaviour down inventory.

**Expected behavior**

Expecting a continuous run of Item numbers.

**Screenshots**

<img width="516" alt="Screenshot 2024-04-29 at 19 50 29" src="https://github.com/rgriebl/brickstore/assets/168474674/ec4b20e4-4e5a-458c-a008-79122dc378f7">

**System information**
Please tell us which system you are running on and which BrickStore version you are using.
In BrickStore, just open `Help` > `System information...`, Click `Copy to clipboard` and then paste  here.

### BrickStore 2024.4.1 (build: 1211)

* **brickstore.ldraw**: 28 Apr 2024 10:33:44 +0100
* **brickstore.locale**: en
* **build.arch**: x86_64
* **build.compiler**: clang 15.0.0 (clang-1500.1.0.2.5)
* **build.date**: 2024-04-05T12:58:55.000
* **build.host**: Mac-1712318843439.local
* **build.number**: 1211
* **build.qt.version**: 6.6.2
* **hw.cpu**: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
* **hw.cpu.arch**: x86_64
* **hw.gpu**: Intel HD Graphics 630
* **hw.gpu.arch**: Intel
* **hw.memory.gb**: 16.0
* **os.arch**: x86_64
* **os.productname**: macOS Ventura (13.6)
* **qt.debug**: false
* **qt.platformname**: cocoa
* **qt.version**: 6.6.2

**Additional context**
You can also attach BSX files, but GitHub only accepts these if added to a ZIP file first.

**Comment by rgriebl** [comment] 2024-04-30 15:52
Duplicate of #860
Next release is right around the corner

**Closed by rgriebl** 2024-04-30 15:52 UTC
