### ISSUE TITLE
I get "Invalid Device information" when logging in

### ISSUE THREAD

**Issue by jaamrode** [rgriebl/brickstore#851] opened 2024-03-28 18:13 UTC
**Describe the bug**
Trying to download my inventory I get "Failed to authenticate with Bricklink as user "...." Invalid Device Information"
notification

**To Reproduce**
1. Click on Inport inventory button

**Expected behavior**
Download my inventory

**Screenshots**

**System information**
### BrickStore 2024.3.1 (build: 1203)

* **brickstore.ldraw**: 13 Mar 2024 13:15:48 -0600
* **brickstore.locale**: en
* **build.arch**: arm64
* **build.compiler**: clang 15.0.0 (clang-1500.1.0.2.5)
* **build.date**: 2024-03-25T23:12:44.000
* **build.host**: Mac-1711406265266.local
* **build.number**: 1203
* **build.qt.version**: 6.6.2
* **hw.cpu**: Apple M1
* **hw.cpu.arch**: arm64
* **hw.gpu**: Apple M1
* **hw.gpu.arch**: sppci_vendor_Apple
* **hw.memory.gb**: 8.0
* **os.arch**: arm64
* **os.productname**: macOS 14.0
* **qt.debug**: false
* **qt.platformname**: cocoa
* **qt.version**: 6.6.2

**Additional context**

**Comment by rgriebl** [comment] 2024-03-28 22:46
Duplicate of #852

**Closed by rgriebl** 2024-03-28 22:46 UTC

**Comment by rgriebl** [comment] 2024-03-29 12:24
See https://www.bricklink.com/message.asp?ID=1461877

> UPDATE:
> 
> The new login procedure was launched as a security feature, but we have rolled
> it back. There should be no issues with Brickstore login at this point.
> 
> Please let us know if you continue to experience problems. Thank you for your
> patience.
