### ISSUE TITLE
Can't import library

### ISSUE THREAD

**Issue by blakbird11** [rgriebl/brickstore#558] opened 2022-06-14 01:21 UTC
Brand new install of 2022.4.1 on clean Windows 8.1 OS.  Cannot import library, SSL handshake issue every time, therefore no functionality.

**Comment by rgriebl** [comment] 2022-06-14 01:25
Duplicate of #409. Please read the last comment there.

**Comment by blakbird11** [comment] 2022-06-14 01:34
Thanks! That was weirdly easy.  Never would have thought of it though.

**Closed** 2022-06-14 10:33 UTC
