### ISSUE TITLE
Price Guide errors lately.

### ISSUE THREAD

**Issue by ZZJHONS** [rgriebl/brickstore#335] opened 2021-04-14 16:57 UTC
Since a few days ago I'm getting errors with Ctrl+G

Sometimes it says that it skipped XX items due to network or errors.

Some other parts show like this:
![image](https://user-images.githubusercontent.com/1063368/114749494-4aefad80-9d53-11eb-8627-3b3a82f9c964.png)

I don't know if this is something from BS, from BL, or from my network (strange...)

**Comment by rgriebl** [comment] 2021-04-14 19:47
That's why I hate HTML scraping: 

![image](https://user-images.githubusercontent.com/3710520/114769680-d163b980-9d6a-11eb-8fdd-e0a8ff04b020.png)

Why would someone remove the `New` text from the current sales table row?

**Comment by rgriebl** [comment] 2021-04-14 19:50
It's even worse. The above screenshot is from BL's online "Add Item" to shop page for 26603 in *black*.
The same 26603 in *lime* shows `New:` perfectly fine though ... wtf?

**Comment by ZZJHONS** [comment] 2021-04-15 10:51
Oh, Bricklink...

The other part that I was having problems with was 98138 in Glitter Trans-Light Blue on Sunday 11th but now it is working fine in BS and in BL...

If it was a source code error why it only happens sometimes...? Maybe this kind of bug you can email BL directly.

**Comment by rgriebl** [comment] 2021-04-15 10:52
I did already. No answer yet though.

**Comment by rgriebl** [comment] 2021-04-16 17:08
This problem seems be solved now. At least I don't get any broken `New:` lines anymore ... even tried it with Sylvain's 6000 lot store contents 3 times in a row.
I *do* however get a lot of `404` not found errors (up to 700 on 6000 lots), but there's no pattern to it (again). I've hacked a simple retry mechanism into BrickStore and now everything seems to download. I hate to do this though, plus I need to do this properly before committing: otherwise we'll have an endless recursion if there happens to be a REAL 404 error ;)

**Comment by RedWolves** [comment] 2021-04-17 00:04
I just ran into this same error while trying to update prices to the price guide.  Skipped because of missing price guide records or network errors.  The number of items skipped is different each time I run the command.  

Running this same command in BrickStock does not produce an error.

**Comment by rgriebl** [comment] 2021-04-17 01:19
BrickStock uses a different interface for downloading PG data. The data you get is wrong though, because that old interface doesn't take VAT into account.

In general, the BL servers are having problems right now: e.g. every time I reload my order list, there are some country flags missing, but - again - the missing flags are never the same.

**Comment by rgriebl** [comment] 2021-04-18 00:02
I've tweaked a few things in the PG DL for build 417. Seems to work for me right now, but the BL servers really are mighty unstable at the moment.
Could you please test if it works out for you as well?

**Comment by ZZJHONS** [comment] 2021-04-18 18:55
9053 lots, it took 11:30 minutes to price, it showed just one error, but sorting the price column it showed 10 items with 0,00€ PG for current.

2420
4865
2412b
44728
85970 this one is missing just the current used PG
86208 missing all current and 6-month used
471905-1 same as 86208 
49595a this shows all values as -
cty1099 same as 86208 
40450-1 same as 86208 

Right click update PG doesn't work

**Comment by rgriebl** [comment] 2021-04-18 21:50
> 2420
> 4865
> 2412b
> 44728
> 85970 this one is missing just the current used PG
> 86208 missing all current and 6-month used

which color? 
You could also quickly check if it's the original error - the missing condition string:  `Ctrl+B,Ctrl+C`, `Add to my inventory`, `Whole Priceguide`

> 471905-1 same as 86208

Has `:` instead of `Used:` (for BOTH current and past 6)

> 49595a this shows all values as -

Has `:` instead of `New:`

> cty1099 same as 86208

Has `:` instead of `Used:`

> 40450-1 same as 86208

Has a price > 1000 with `,` as a thousands separator. Had to change the parsing locale. -> Fixed in next build.

> 
> Right click update PG doesn't work

**Comment by ZZJHONS** [comment] 2021-04-19 15:39
@rgriebl I emailed you a BSX file with my store's 9k lots.

**Comment by rgriebl** [comment] 2021-04-20 10:37
The latest build seems to be able dodge around all the weird BL server problems at the moment. Please give it a try.

There's one corner case that I could not trigger though: an item where PG data is only available for `Used` and BL's PG page dropping the `Used` string. An item like this would end up having the `used` data as `new` and no `used` data in BrickStore.

**Comment by ZZJHONS** [comment] 2021-04-20 16:55
Done, it took 9 minutes for 9k lots, but 0 errors :D

**Comment by rgriebl** [comment] 2021-04-20 17:12
Can't do anything about the slowness: I've added HTTP/2 support, enabled HTTP pipelineing and I add SSL session caching. It all helps a little, but the BL servers cannot handle more than 4 requests in parallel right now (6 is the industry standard, as implemented in every browser).

**Closed** 2021-04-20 17:12 UTC

**Comment by rgriebl** [comment] 2021-04-26 18:13
Finally got a reply from BL support: "[...] there's nothing we can do to assist you and would advise contacting the developers for BrickStore. "
Yeah ... about that.

**Comment by rgriebl** [comment] 2021-04-27 20:24
And another (positive) update from BL support: they can reproduce the bug and the dev team is looking into it. No ETA though due to the ongoing VAT/Brexit work.

**Comment by ZZJHONS** [comment] 2021-08-12 18:41
@rgriebl An update from two days ago says they fixed it:

https://www.bricklink.com/help.asp?helpID=2453
