### ISSUE TITLE
Could not parse the received order XML

### ISSUE THREAD

**Issue by jjcchh754** [rgriebl/brickstore#776] opened 2023-09-30 07:47 UTC
HI

When i try to import all orders, (Wich I use to do 2 per day). But today I got this meesage:

Last update failed: Could not parse the received order XML data: XML parse error at line 7254, column 41: Expected '#' or '[a-zA-Z]', but got ' '.

Is this something you could look at? 

Best regards,
Johan

**Comment by rgriebl** [comment] 2023-09-30 09:56
Duplicate of #615
Still a BrickLink bug, but the chances of them fixing all their broken XML escaping after all these years is probably zero.
Nothing I can do about though.

**Closed by rgriebl** 2023-09-30 09:56 UTC

**Comment by jjcchh754** [comment] 2023-09-30 18:51
Hey
The problem is that i cant read in orders at all due to this error. Is there any chance to just skip that order and continue with next order or so. As it is now I cant use brickstore for workin with orders at all :)
Best regards
johan
